version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
    username: dummy # Required by dependabot
    password: dummy # Required by dependabot
  maven-central:
    type: maven-repository
    url: https://repo1.maven.org/maven2/
    username: dummy # Required by dependabot
    password: dummy # Required by dependabot
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "1.0.x" # oldest OSS supported branch
    schedule:
      interval: "weekly"
  # Build dependencies
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    target-branch: 1.0.x
    groups:
      netflix-plugins:
        patterns:
          - "com.netflix.nebula*"
        update-types:
          - minor
          - patch
    allow:
      - dependency-name: "gradle.plugin.com.hierynomus.gradle.plugins*"
      - dependency-name: "com.netflix.nebula*"
      - dependency-name: "io.spring.nohttp*"
      - dependency-name: "io.github.gradle-nexus*"
      - dependency-name: "io.spring.javaformat*"
      - dependency-name: "io.spring.ge.conventions*"
      - dependency-name: "com.gradle*"
      - dependency-name: "org.gradle*"
    ignore:
      # only upgrade minor and patch versions for build dependencies
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    registries:
      - gradle-plugin-portal
      - maven-central
    milestone: 1.0.x
  # Non-build dependencies maintenance branch
  - package-ecosystem: gradle
    directory: /gradle
    schedule:
      interval: daily
    target-branch: 1.0.x
    ignore:
      # newer versions do not support Java 8
      - dependency-name: "org.jboss.forge.roaster:roaster-api"
      # only upgrade patch versions
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    milestone: 1.0.x
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    target-branch: main
    ignore:
      # newer versions do not support Java 8
      - dependency-name: "org.jboss.forge.roaster:roaster-api"
      # only upgrade by minor or patch
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    milestone: 1.1.x
