version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "1.1.x" # oldest OSS supported branch
    schedule:
      interval: "weekly"
# Non-build dependencies; target every supported branch
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    target-branch: "main"
    milestone: 14
    ignore:
      # newer versions do not support Java 8
      - dependency-name: "org.jboss.forge.roaster:roaster-api"
      # upgrade minor and patch versions on main
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 5
